In [1]:
import numpy as np
import os
import pandas as pd
import arcpy

#import arcgis libraries for Spatially-Enabled DataFrames
from arcgis.gis import *
gis = GIS()

In [2]:
working_directory = os.getcwd()
dataTAZ_directory = os.path.join(working_directory,"data\TAZ")
intrmed_directory = os.path.join(working_directory,"intermediate")
results_directory = os.path.join(working_directory,"results"     )

print(working_directory)

sltaz_shp = r"A:\1 - TDM\1 - Input Dev\0 - GlobalData\0 - TripTables\1 - Colleges\data\StreetLight_TAZ_2021_09_22\StreetLight_TAZ_2021_09_22.shp"
sltaz_centroids_shp = r"A:\1 - TDM\1 - Input Dev\0 - GlobalData\0 - TripTables\1 - Colleges\data\StreetLight_TAZ_2021_09_22\StreetLight_TAZ_2021_09_22_centroids.shp"

#tazcentroids_shp = r"E:\GitHub\TDM-College-Enrollment-v9\TAZ\USTM_TAZ_2021_09_22_Centroids.shp";

#results
csv_tazzip = os.path.join(intrmed_directory, r"SLTAZ20210922_zipcode.csv")

a:\1 - TDM\1 - Input Dev\0 - GlobalData\0 - TripTables\1 - Colleges

In [3]:
sdfSLTAZ = pd.DataFrame.spatial.from_featureclass(sltaz_shp)
sdfSLTAZ

,FID,TAZID,SA_TAZID,CO_IDX,CO_TAZID,SL_SPLIT,SL_TAZID,SL_COTAZID,SUBAREAID,ACRES,...,SORT,TAZID_V21B,SATAZ_V21B,COTAZ_V21B,SUBID_V21B,TAZID_V21A,SATAZ_V21A,COTAZ_V21A,SUBID_V21A,SHAPE
0,0,43,3,3,1003,0.0,43.00,1003_0,0,440.680556,...,1.0,43,0,1013,0,43,0,1013,0,"{""rings"": [[[357893.0658495235, 4241258.596375..."
1,1,45,5,5,1005,0.0,45.00,1005_0,0,245.424579,...,2.0,45,0,1015,0,45,0,1015,0,"{""rings"": [[[356154.68735317234, 4239646.44397..."
2,2,46,6,6,1006,0.0,46.00,1006_0,0,675.848293,...,3.0,46,0,1016,0,46,0,1016,0,"{""rings"": [[[356651.1987523214, 4239664.663077..."
3,3,55,15,15,1015,0.0,55.00,1015_0,0,550.767119,...,4.0,55,0,1025,0,55,0,1025,0,"{""rings"": [[[356587.7144537966, 4236519.618983..."
4,4,50,10,10,1010,0.0,50.00,1010_0,0,176.207617,...,5.0,50,0,1020,0,50,0,1020,0,"{""rings"": [[[356438.3099536191, 4237510.316581..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10223,10223,9569,74,74,21074,0.0,9569.00,21074_0,5,11.750705,...,10224.0,8572,73,21073,5,1226,0,21018,0,"{""rings"": [[[318929.0193047933, 4179714.800154..."
10224,10224,9854,359,359,21359,2.0,9854.02,21359_2,5,455.391284,...,10225.0,8853,354,21354,5,1442,0,21234,0,"{""rings"": [[[338591.27629957534, 4165081.85682..."
10225,10225,9854,359,359,21359,3.0,9854.03,21359_3,5,175.557628,...,10226.0,8853,354,21354,5,1442,0,21234,0,"{""rings"": [[[338041.0140583487, 4164399.726681..."
10226,10226,9793,298,298,21298,0.0,9793.00,21298_0,5,1011.540449,...,10227.0,8795,296,21296,5,1462,0,21254,0,"{""rings"": [[[341906.2369978158, 4192672.782851..."
10227,10227,9794,299,299,21299,0.0,9794.00,21299_0,5,691.356049,...,10228.0,8787,288,21288,5,1466,0,21258,0,"{""rings"": [[[340050.871300227, 4194333.8565475..."

In [6]:
# create shapefile of taz centroids
#arcpy.management.FeatureToPoint(sltaz_shp, sltaz_centroids_shp, "INSIDE")

In [7]:
sdfSLTAZCentroids = pd.DataFrame.spatial.from_featureclass(sltaz_centroids_shp)
sdfSLTAZCentroids

,FID,TAZID,SA_TAZID,CO_IDX,CO_TAZID,SL_SPLIT,SL_TAZID,SL_COTAZID,SUBAREAID,ACRES,...,TAZID_V21B,SATAZ_V21B,COTAZ_V21B,SUBID_V21B,TAZID_V21A,SATAZ_V21A,COTAZ_V21A,SUBID_V21A,ORIG_FID,SHAPE
0,0,43,3,3,1003,0.0,43.00,1003_0,0,440.680556,...,43,0,1013,0,43,0,1013,0,0,"{""x"": 357308.6182651231, ""y"": 4240407.88900315..."
1,1,45,5,5,1005,0.0,45.00,1005_0,0,245.424579,...,45,0,1015,0,45,0,1015,0,1,"{""x"": 356023.3334507849, ""y"": 4239022.55291350..."
2,2,46,6,6,1006,0.0,46.00,1006_0,0,675.848293,...,46,0,1016,0,46,0,1016,0,2,"{""x"": 357530.3066370487, ""y"": 4239070.37350970..."
3,3,55,15,15,1015,0.0,55.00,1015_0,0,550.767119,...,55,0,1025,0,55,0,1025,0,3,"{""x"": 356277.25434629526, ""y"": 4234918.1938378..."
4,4,50,10,10,1010,0.0,50.00,1010_0,0,176.207617,...,50,0,1020,0,50,0,1020,0,4,"{""x"": 355998.11915513594, ""y"": 4237044.8358589..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10223,10223,9569,74,74,21074,0.0,9569.00,21074_0,5,11.750705,...,8572,73,21073,5,1226,0,21018,0,10223,"{""x"": 319032.24395555817, ""y"": 4179828.5837015..."
10224,10224,9854,359,359,21359,2.0,9854.02,21359_2,5,455.391284,...,8853,354,21354,5,1442,0,21234,0,10224,"{""x"": 338247.3727782853, ""y"": 4166304.95361812..."
10225,10225,9854,359,359,21359,3.0,9854.03,21359_3,5,175.557628,...,8853,354,21354,5,1442,0,21234,0,10225,"{""x"": 337319.4509811513, ""y"": 4164091.60752435..."
10226,10226,9793,298,298,21298,0.0,9793.00,21298_0,5,1011.540449,...,8795,296,21296,5,1462,0,21254,0,10226,"{""x"": 341718.9014489893, ""y"": 4191679.73777361..."
10227,10227,9794,299,299,21299,0.0,9794.00,21299_0,5,691.356049,...,8787,288,21288,5,1466,0,21258,0,10227,"{""x"": 339940.31446972117, ""y"": 4193627.0721040..."

# Read in Zip Codes

In [11]:
sde_filename = "agrc_opensgid"

#make only once
arcpy.CreateDatabaseConnection_management (intrmed_directory, sde_filename, "POSTGRESQL", "opensgid.agrc.utah.gov", "DATABASE_AUTH", "agrc", "agrc", "SAVE_USERNAME", "opensgid")

In [12]:
zipcodearea_layername = "intrmed_directory\\opensgid.boundaries.zip_code_areas"
zipcode = sde_filename + ".sde\\" + zipcodearea_layername
print(arcpy.Describe(zipcode).shapeType)

sdfZipCode = pd.DataFrame.spatial.from_featureclass(zipcode)
sdfZipCode

Polygon

,xid,countynbr,name,symbol,zip5,SHAPE
0,1,20,AXTELL,1,84621,"{""rings"": [[[425018.0700000003, 4328798.35], [..."
1,2,20,CENTERFIELD,2,84622,"{""rings"": [[[437052.7000000002, 4326967.91], [..."
2,3,20,GUNNISON,4,84634,"{""rings"": [[[439755.2999999998, 4343323.199999..."
3,4,14,LEAMINGTON,5,84638,"{""rings"": [[[396208.1799999997, 4373824.83], [..."
4,5,14,GARRISON,4,84728,"{""rings"": [[[305018.38999999966, 4380551.18], ..."
...,...,...,...,...,...,...
296,297,18,TAYLORSVILLE,4,84129,"{""rings"": [[[420660.11000000034, 4503894.31000..."
297,298,9,PANGUITCH,1,84759,"{""rings"": [[[373455.53000000026, 4223442.78999..."
298,299,18,SOUTH JORDAN,3,84009,"{""rings"": [[[417304.0800000001, 4492637.52], [..."
299,300,25,OREM,5,84058,"{""rings"": [[[437951.20999999996, 4460934.15], ..."
300,301,27,MOTOQUA,2,84765,"{""rings"": [[[235239.66000000015, 4138488.51999..."

In [ ]:
#sdfZipCode.spatial.to_featureclass(os.path.join(intrmed_directory,'ugrc_zip_codes.shp'))

'a:\\1 - TDM\\1 - Input Dev\\0 - GlobalData\\0 - TripTables\\1 - Colleges\\intermediate\\ugrc_zip_codes.shp'

In [13]:
sdfTAZCentroids_ZipCode = sdfSLTAZCentroids.spatial.join(sdfZipCode)
sdfTAZCentroids_ZipCode

,FID,TAZID,SA_TAZID,CO_IDX,CO_TAZID,SL_SPLIT,SL_TAZID,SL_COTAZID,SUBAREAID,ACRES,...,COTAZ_V21A,SUBID_V21A,ORIG_FID,SHAPE,index_right,xid,countynbr,name,symbol,zip5
0,0,43,3,3,1003,0.0,43.0,1003_0,0,440.680556,...,1013,0,0,"{""x"": 357308.6182651231, ""y"": 4240407.88900315...",203,204,1,BEAVER,5,84713
1,1,45,5,5,1005,0.0,45.0,1005_0,0,245.424579,...,1015,0,1,"{""x"": 356023.3334507849, ""y"": 4239022.55291350...",203,204,1,BEAVER,5,84713
2,2,46,6,6,1006,0.0,46.0,1006_0,0,675.848293,...,1016,0,2,"{""x"": 357530.3066370487, ""y"": 4239070.37350970...",203,204,1,BEAVER,5,84713
3,3,55,15,15,1015,0.0,55.0,1015_0,0,550.767119,...,1025,0,3,"{""x"": 356277.25434629526, ""y"": 4234918.1938378...",203,204,1,BEAVER,5,84713
4,4,50,10,10,1010,0.0,50.0,1010_0,0,176.207617,...,1020,0,4,"{""x"": 355998.11915513594, ""y"": 4237044.8358589...",203,204,1,BEAVER,5,84713
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10223,10076,9500,5,5,21005,0.0,9500.0,21005_0,5,16771.166796,...,21145,0,10076,"{""x"": 249570.0175539162, ""y"": 4182116.65286246...",110,111,11,MODENA,2,84753
10224,10009,9821,326,326,21326,0.0,9821.0,21326_0,5,2675.544250,...,21245,0,10009,"{""x"": 328405.12375525944, ""y"": 4187011.4908026...",202,203,11,SUMMIT,2,84772
10225,10019,9831,336,336,21336,0.0,9831.0,21336_0,5,24845.539473,...,21240,0,10019,"{""x"": 333493.2796775652, ""y"": 4180601.23975288...",202,203,11,SUMMIT,2,84772
10226,10028,9826,331,331,21331,0.0,9826.0,21331_0,5,715.142241,...,21224,0,10028,"{""x"": 326061.1637930721, ""y"": 4183325.71482209...",202,203,11,SUMMIT,2,84772
10227,10029,9827,332,332,21332,0.0,9827.0,21332_0,5,1903.024070,...,21241,0,10029,"{""x"": 329120.0241910061, ""y"": 4184975.81540805...",202,203,11,SUMMIT,2,84772

In [14]:
dfTAZZip = sdfTAZCentroids_ZipCode[['SL_COTAZID','zip5']]
dfTAZZip.to_csv(csv_tazzip,index=False)
dfTAZZip

      SL_COTAZID   zip5
0         1003_0  84713
1         1005_0  84713
2         1006_0  84713
3         1015_0  84713
4         1010_0  84713
...          ...    ...
10223    21005_0  84753
10224    21326_0  84772
10225    21336_0  84772
10226    21331_0  84772
10227    21332_0  84772

[10228 rows x 2 columns]

In [16]:
#create map centered on Salt Lake
map_areas = gis.map('Salt Lake')

#define sdf layer


sdfZipCode.spatial.plot(map_widget = map_areas,
                        renderer_type='s',
                        cmap = 'RdPu',  # use a red to purple color map
                        symbol_type='simple',
                        outline_style='s',
                        outline_color=[0,0,0,255],
                        line_width=1.0)

#sdfSLTAZ.spatial.plot(map_widget = map_areas,
#                      renderer_type='s',
#                      cmap = 'Greens',  # use a red to purple color map
#                      symbol_type='simple',
#                      outline_style='s',
#                      outline_color=[0,0,0,255],
#                      line_width=1.0)
#
#sdfTAZCentroids_ZipCode.spatial.plot(map_widget = map_areas,
#                                     renderer_type='s',
#                                     cmap = 'RdPu',  # use a red to purple color map
#                                     symbol_type='simple',
#                                     outline_style='s',
#                                     outline_color=[0,0,0,255],
#                                     line_width=1.0)


#define map characteristics
map_areas.layout.height='500px'
map_areas.legend=True

#display map
map_areas

MapView(layout=Layout(height='500px', width='100%'), legend=True)