In [13]:
import pandas as pd
import os
import numpy as np

In [14]:
working_directory = os.getcwd()
print(working_directory)

a:\1 - TDM\1 - Input Dev\0 - GlobalData\0 - TripTables\1 - College Base Year Enrollment Distribution

In [15]:
# Read 2020 csv as pandas dataframe object
data_folder = os.path.join(os.getcwd(), r'data\USHE 2020 Enrollment')
int_folder = os.path.join(os.getcwd(), r'intermediate')
csv_enrol = os.path.join(data_folder, 'headcount.csv')
df_enrol = pd.read_csv(csv_enrol)

In [16]:
dfCampusCodes = pd.DataFrame([
                  ['SLCC','Main Campus'                ,'SLCC_MAIN'],
                  ['SLCC','SLCC Larry H. Miller Campus','SLCC_ML'  ],
                  ['SLCC','SLCC South City Center'     ,'SLCC_SC'  ],
                  ['SLCC','SLCC Jordan Campus'         ,'SLCC_JD'  ],
                  ['UU'  ,'Main Campus'                ,'UOFU_MAIN'],
                  ['UVU' ,'Main Campus'                ,'UVU_MAIN' ],
                  ['WSU' ,'Main Campus'                ,'WSU_MAIN' ],
                  ['WSU' ,'WSU Davis Center'           ,'WSU_DAVIS']
                ],columns=['Institution','Site','COLLEGE'])

dfCampusCodes

  Institution                         Site    COLLEGE
0        SLCC                  Main Campus  SLCC_MAIN
1        SLCC  SLCC Larry H. Miller Campus    SLCC_ML
2        SLCC       SLCC South City Center    SLCC_SC
3        SLCC           SLCC Jordan Campus    SLCC_JD
4          UU                  Main Campus  UOFU_MAIN
5         UVU                  Main Campus   UVU_MAIN
6         WSU                  Main Campus   WSU_MAIN
7         WSU             WSU Davis Center  WSU_DAVIS

In [17]:
# Show the first 5 rows of a table
df_enrol.head()

,Institution,Site,Academic_Year,Term,ZIP_Code,Full_or_Part_Time,Headcount
0,SLCC,Draper,2020,2,84020,Part-Time,2
1,SLCC,Draper,2020,2,84070,Part-Time,1
2,SLCC,Draper,2020,2,84104,Part-Time,1
3,SLCC,Draper,2020,2,84107,Part-Time,1
4,SLCC,Draper,2020,2,84124,Part-Time,1

In [18]:
df_enrol.groupby('Institution').agg({'Headcount': [np.size, np.sum]})

            Headcount
                 size    sum
Institution
SLCC             1194  22560
USU               343   1238
UU                445  28932
UVU               354  25217
WSU               636  17138

In [19]:
df_enrol.groupby(['Institution','Site']).agg({'Headcount': [np.size, np.sum]})

                                                               Headcount  \
                                                                    size
Institution Site
SLCC        Draper                                                     5
            Main Campus                                              235
            SLCC Airport Center                                       75
            SLCC Herriman Center                                      47
            SLCC Jordan Campus                                       187
            SLCC Larry H. Miller Campus                              161
            SLCC Library Square Center (Previously Main Str...        97
            SLCC Meadowbrook Campus                                   31
            SLCC South City Center                                   175
            SLCC West Point Center                                   122
            SLCC West Valley City                                     59
USU         Mountainland Technical College                            19
            USU Brigham Center                                       109
            USU Ogden Center                                          67
            USU Orem Center                                           31
            USU Salt Lake Center                                      90
            USU Tooele Center                                         27
UU          Main Campus                                              357
            UofU Sandy Center                                         88
UVU         Main Campus                                              354
WSU         Davis Technical College                                   26
            Main Campus                                              299
            Ogden-Weber Technical College                             12
            SLCC                                                      47
            WSU Davis Center                                         164
            WSU Farmington Station                                    56
            WSU West Center                                           32


                                                                  sum
Institution Site
SLCC        Draper                                                  6
            Main Campus                                         11910
            SLCC Airport Center                                   129
            SLCC Herriman Center                                  283
            SLCC Jordan Campus                                   4166
            SLCC Larry H. Miller Campus                          1038
            SLCC Library Square Center (Previously Main Str...    303
            SLCC Meadowbrook Campus                                49
            SLCC South City Center                               3694
            SLCC West Point Center                                509
            SLCC West Valley City                                 473
USU         Mountainland Technical College                         24
            USU Brigham Center                                    464
            USU Ogden Center                                      202
            USU Orem Center                                        80
            USU Salt Lake Center                                  272
            USU Tooele Center                                     196
UU          Main Campus                                         28166
            UofU Sandy Center                                     766
UVU         Main Campus                                         25217
WSU         Davis Technical College                                63
            Main Campus                                         12887
            Ogden-Weber Technical College                          27
            SLCC                                                   91
            WSU Davis Center                                     3388
            WSU Farmington Station                                343
            WSU West Center                                       339

In [20]:
df_enrol.groupby(['Institution','Site']).agg({'Headcount': [np.size, np.sum]}).sum()

Headcount  size     2972
           sum     95085
dtype: int64

In [21]:
df_enrol[(df_enrol['Institution'] == 'UU') & (df_enrol['Site'] == 'Main Campus')].groupby(['Institution','Site','ZIP_Code']).agg({'Headcount': [np.size, np.sum]})

                                 Headcount
                                      size  sum
Institution Site        ZIP_Code
UU          Main Campus 84003            2  252
                        84004            2   67
                        84005            2   92
                        84006            2    7
                        84007            1    1
...                                    ...  ...
                        84780            2   20
                        84781            1    1
                        84782            1    1
                        84783            1    1
                        84790            2   72

[214 rows x 2 columns]

In [22]:
dfTotEnrolByZip = df_enrol.groupby(['Institution','Site','ZIP_Code'],as_index=False).agg(TotEnrol=('Headcount','sum'))
dfTotEnrolByZip.to_csv(os.path.join(int_folder,'campus_totenrol_byzip.csv'),index=False)
dfTotEnrolByZip

     Institution             Site  ZIP_Code  TotEnrol
0           SLCC           Draper     84020         2
1           SLCC           Draper     84070         1
2           SLCC           Draper     84104         1
3           SLCC           Draper     84107         1
4           SLCC           Draper     84124         1
...          ...              ...       ...       ...
2082         WSU  WSU West Center     84403        22
2083         WSU  WSU West Center     84404        16
2084         WSU  WSU West Center     84405        19
2085         WSU  WSU West Center     84408         1
2086         WSU  WSU West Center     84414        18

[2087 rows x 4 columns]

In [23]:
dfTotEnrolByZip_College = pd.DataFrame.merge(dfCampusCodes,dfTotEnrolByZip,on=['Institution','Site'])
dfTotEnrolByZip_College = dfTotEnrolByZip_College.drop(columns=(['Institution','Site']))
dfTotEnrolByZip_College

        COLLEGE  ZIP_Code  TotEnrol
0     SLCC_MAIN     84003        61
1     SLCC_MAIN     84004        20
2     SLCC_MAIN     84005        57
3     SLCC_MAIN     84006         4
4     SLCC_MAIN     84009       249
...         ...       ...       ...
1192  WSU_DAVIS     84765         1
1193  WSU_DAVIS     84770         3
1194  WSU_DAVIS     84780         2
1195  WSU_DAVIS     84784         1
1196  WSU_DAVIS     84790         1

[1197 rows x 3 columns]

In [25]:
dfTotEnrolByZip_College.to_csv(os.path.join(int_folder,'TotEnrolByZipByCollege.csv'),index=False)