# Libraries and Global Variables

In [ ]:
import pandas as pd
import os
import numpy as np

# import matplotlib.ticker as mtick
from IPython.display import display, Markdown

# import arcgis libraries
from arcgis.gis import *

gis = GIS()

In [ ]:
working_directory = os.getcwd()
data_folder = os.path.join(working_directory, "data")
intermediate_folder = os.path.join(working_directory, "intermediate")
results_folder = os.path.join(working_directory, "results")

shp_taz = r"K:\TDM\0 - ModelDev\2 - Sandbox\v9.0Beta\01 - Input Dev\1_TAZ\Update_TAZ - 2021-11-08 - Update Subarea\0 - USTM_v2.1d - 2021-09-22\USTM_TAZ_2021_09_22.shp"

print(working_directory)
print(data_folder)
print(results_folder)

d:\GitHub\TDM-INP-College-Enrollment
d:\GitHub\TDM-INP-College-Enrollment\data
d:\GitHub\TDM-INP-College-Enrollment\results

# Student Housing - Dorms

In [3]:
# https://services1.arcgis.com/99lidPhWCzftIe9K/arcgis/rest/services/CensusBlocks2020/FeatureServer
item = gis.content.get("2caf01e704614114868a3d801b82def6")
flayer = item.layers[0]

# create a Spatially Enabled DataFrame object
sdfUtahCensusBlocks2020 = pd.DataFrame.spatial.from_layer(flayer)

C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services1.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [ ]:
# GQ_STUDENT is P0050008 College/University student housing
# filter out everything except student housing
sdfUtahCensusBlocks2020 = sdfUtahCensusBlocks2020[
    sdfUtahCensusBlocks2020["GQ_STUDENT"] > 0
]
display(sdfUtahCensusBlocks2020)
display(sdfUtahCensusBlocks2020.columns)
sdfUtahCensusBlocks2020.spatial.to_featureclass(
    os.path.join(intermediate_folder, "groupquarter_censusblocks_2020.shp")
)

,OBJECTID,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,...,GQ_JUVCOR,GQ_NURS,GQ_INSOTH,GQ_TOTNIN,GQ_STUDENT,GQ_MILTARY,GQ_NINOTH,Shape__Area,Shape__Length,SHAPE
443,14000,49,049,001802,3008,490490018023008,Block 3008,G5040,,,...,0,0,0,687,687,0,0,4676.835938,312.074139,"{""rings"": [[[-12429007.6672, 4901048.1132], [-..."
908,35141,49,049,001802,3006,490490018023006,Block 3006,G5040,,,...,0,0,0,121,121,0,0,3937.941406,259.465443,"{""rings"": [[[-12428864.5104, 4901079.4675], [-..."
1514,42906,49,049,001105,2009,490490011052009,Block 2009,G5040,,,...,0,0,0,246,246,0,0,10589.273438,417.164575,"{""rings"": [[[-12437162.7127, 4907609.4516], [-..."
1617,7551,49,049,001802,4002,490490018024002,Block 4002,G5040,,,...,0,0,0,13,13,0,0,9262.539062,397.578533,"{""rings"": [[[-12428387.6176, 4901071.155], [-1..."
1709,37302,49,021,110400,2001,490211104002001,Block 2001,G5040,,,...,0,0,0,59,59,0,0,9935.578125,401.295483,"{""rings"": [[[-12586811.8379, 4533506.4908], [-..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49981,62929,49,019,000302,2411,490190003022411,Block 2411,G5040,,,...,0,0,0,40,24,0,16,760134.0625,4347.758752,"{""rings"": [[[-12176552.2425, 4670635.9822], [-..."
50673,29147,49,019,000302,2329,490190003022329,Block 2329,G5040,,,...,0,0,0,7,7,0,0,1080017.238281,4603.989676,"{""rings"": [[[-12179612.6386, 4671324.3994], [-..."
51016,5841,49,037,942100,1079,490379421001079,Block 1079,G5040,,,...,0,0,0,37,37,0,0,1436856.878906,4949.460847,"{""rings"": [[[-12265789.6196, 4439771.2294], [-..."
55617,8242,49,035,101402,2003,490351014022003,Block 2003,G5040,,,...,0,0,0,375,375,0,0,1868316.332031,7705.10146,"{""rings"": [[[-12451347.9426, 4977135.2523], [-..."
65524,46002,49,035,115109,1032,490351151091032,Block 1032,G5040,,,...,0,0,0,32,32,0,0,3041533.738281,13391.702835,"{""rings"": [[[-12466011.3903, 4936721.2187], [-..."

Index(['OBJECTID', 'STATEFP20', 'COUNTYFP20', 'TRACTCE20', 'BLOCKCE20',
       'GEOID20', 'NAME20', 'MTFCC20', 'UR20', 'UACE20', 'UATYPE20',
       'FUNCSTAT20', 'ALAND20', 'AWATER20', 'INTPTLAT20', 'INTPTLON20',
       'LOGRECNO', 'PP_TOTAL', 'PP_SNRACE', 'PP_WHTALN', 'PP_BAAALN',
       'PP_NAMALN', 'PP_ASNALN', 'PP_HPIALN', 'PP_OTHALN', 'PP_MTRACE',
       'PP_HISPLAT', 'PP_AGGTE18', 'HU_TOTAL', 'HU_OCC', 'HU_VAC', 'GQ_TOTAL',
       'GQ_TOTINS', 'GQ_ADLTCOR', 'GQ_JUVCOR', 'GQ_NURS', 'GQ_INSOTH',
       'GQ_TOTNIN', 'GQ_STUDENT', 'GQ_MILTARY', 'GQ_NINOTH', 'Shape__Area',
       'Shape__Length', 'SHAPE'],
      dtype='object')

C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\arcgis\features\geo\_accessor.py:1606: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._data[col] = array
C:\Users\Pukar.Bhandari\AppData\Local\miniconda3\envs\wfrc\Lib\site-packages\osgeo\gdal.py:311: FutureWarning: Neither gdal.UseExceptions() nor gdal.DontUseExceptions() has been explicitly called. In GDAL 4.0, exceptions will be enabled by default.
  warnings.warn(

'd:\\GitHub\\TDM-INP-College-Enrollment\\intermediate\\groupquarter_censusblocks_2020.shp'

In [ ]:
# create column with x and y coordinates of centroids
sdfUtahCensusBlocks2020_centroid = sdfUtahCensusBlocks2020[
    ["GEOID20", "SHAPE", "GQ_STUDENT"]
].copy()
sdfUtahCensusBlocks2020_centroid["x_lon"] = sdfUtahCensusBlocks2020_centroid.apply(
    lambda row: row.SHAPE.centroid[0], axis=1
)
sdfUtahCensusBlocks2020_centroid["y_lat"] = sdfUtahCensusBlocks2020_centroid.apply(
    lambda row: row.SHAPE.centroid[1], axis=1
)

sdfUtahCensusBlocks2020_centroid.head()
sdfUtahCensusBlocks2020_centroid.spatial.to_featureclass(
    os.path.join(intermediate_folder, "groupquarter_censusblocks_2020_centroids.shp")
)

,GEOID20,SHAPE,GQ_STUDENT,x_lon,y_lat
1156,490490011032007,"{""rings"": [[[-12435869.2912, 4906034.4025], [-...",300,-1.243531e+07,4.905932e+06
1894,490490019001009,"{""rings"": [[[-12430088.9137, 4901842.0633], [-...",596,-1.242995e+07,4.901760e+06
2826,490532713002001,"{""rings"": [[[-12642389.8789, 4453525.5358], [-...",461,-1.264200e+07,4.453626e+06
3315,490050007021005,"{""rings"": [[[-12447156.2215, 5122260.5425], [-...",388,-1.244661e+07,5.122489e+06
4049,490050007022001,"{""rings"": [[[-12446543.2963, 5123838.5001], [-...",11,-1.244627e+07,5.123725e+06

In [ ]:
sdfTAZ = pd.DataFrame.spatial.from_featureclass(shp_taz)
sdfTAZ

,FID,TAZID,SA_TAZID,CO_IDX,CO_TAZID,SUBAREAID,ACRES,DEVACRES,DEVPBLEPCT,X,...,SORT,TAZID_V21B,SATAZ_V21B,COTAZ_V21B,SUBID_V21B,TAZID_V21A,SATAZ_V21A,COTAZ_V21A,SUBID_V21A,SHAPE
0,0,43,3,3,1003,0,440.680556,440.680556,1.00,357308.618265,...,1,43,0,1013,0,43,0,1013,0,"{""rings"": [[[357893.0658, 4241258.5964], [3578..."
1,1,45,5,5,1005,0,245.424579,245.424579,1.00,356023.333451,...,2,45,0,1015,0,45,0,1015,0,"{""rings"": [[[356154.68740000017, 4239646.444],..."
2,2,46,6,6,1006,0,675.848293,675.848293,1.00,357530.306637,...,3,46,0,1016,0,46,0,1016,0,"{""rings"": [[[356651.19880000036, 4239664.66310..."
3,3,55,15,15,1015,0,550.767119,534.244106,0.97,356277.254346,...,4,55,0,1025,0,55,0,1025,0,"{""rings"": [[[356587.71449999977, 4236519.61900..."
4,4,50,10,10,1010,0,176.207617,176.207617,1.00,355998.119155,...,5,50,0,1020,0,50,0,1020,0,"{""rings"": [[[356438.3099999996, 4237510.316600..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9810,9810,9615,120,120,21120,5,18.530419,18.530419,1.00,317587.467931,...,9811,8618,119,21119,5,1241,0,21033,0,"{""rings"": [[[317686.84169999976, 4175673.97079..."
9811,9811,9634,139,139,21139,5,104.810861,79.656255,0.76,318283.808626,...,9812,8636,137,21137,5,1259,0,21051,0,"{""rings"": [[[318534.3049999997, 4175205.747400..."
9812,9812,9569,74,74,21074,5,11.750705,11.750705,1.00,319032.243956,...,9813,8572,73,21073,5,1226,0,21018,0,"{""rings"": [[[318929.0192999998, 4179714.800200..."
9813,9813,9793,298,298,21298,5,1011.540449,920.501809,0.91,341575.123412,...,9814,8795,296,21296,5,1462,0,21254,0,"{""rings"": [[[341906.23699999973, 4192672.7829]..."
9814,9814,9794,299,299,21299,5,691.356049,691.356049,1.00,339940.314470,...,9815,8787,288,21288,5,1466,0,21258,0,"{""rings"": [[[340050.87129999977, 4194333.8565]..."